### ISSUE TITLE
Tagging system to assist search queries

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/nkd.su#148]
A lot of shows are known by various portions of the anime community by either the Japanese name or the English name, and in a lot of cases, the tracks are tagged with one or the other, not both. This means if someone searches for the wrong one, the track won't show up.

So the idea is, have tags that tracks can have so the tracks show up when you search for it by the tag. This means I can have only one anime title (probably the Japanese) in the main metadata, but then the tags can have the English title and sometimes the short form of the name (Konosuba, Oreimo, etc).

If the search matches the tag, the tag should be displayed next to the track on the search page probably, and maybe all searchable tags are shown on the track pages.

**Comment by theshillito** [comment]
Had another thought on this: each tag should have a type and a content. type could be "English Anime Name" or "English Song Title" (i have had at least one report of someone searching for a track by the translated song title) or "anime short name", etc.

**Comment by theshillito** [comment]
Mockup image as an example of a track with a single tag: 
![screen shot 2017-12-30 at 20 07 15](https://user-images.githubusercontent.com/1828418/34457032-4b9d2898-ed9d-11e7-9ef1-282d81b7abd8.png)

**Comment by homsar** [comment]
For tags that every song would benefit from having, is it worth defining these as an extra database column rather than through a tag system, which would seem more ad-hoc? This would then allow better standardisation on whether English or Japanese anime titles were used, which has been discussed previously. It may need #78 to be resolved to make it practical though.

**Comment by theshillito** [comment]
Potentially this could be a local toggle using a cookie or equivalent if someone wants only English titles perhaps. Another thing worth considering is trying to connect with an API somewhere to look up a title in another language based on one supplied. Then there could be a straightforward language toggle and it be all automatic.

**Comment by colons** [comment]
Now that we have (for the most part?) good, consistent anime names derivable from tracks, pulling alternative titles from anilist or something sounds extremely achievable and worth exploring. Would be pretty simple to keep it totally independent of the actual library, too.

Very early versions of nkd.su had database fields for this stuff, but they were never populated :<

**Comment by theshillito** [comment]
Anilist API v2 (v1 is depreciated): https://github.com/AniList/ApiV2-GraphQL-Docs

**Comment by theshillito** [comment]
Tags should apply to anime, artist or individual tracks.

**Comment by theshillito** [comment]
There are three tickets at the time of posting that could be resolved by a tagging system:

-  Mark tracks as instrumental #215 
-  A way to tag songs as being radio-friendly where applicable #225 
-  Track the language/s each song is sung in #285 

A single tagging system would make sense here rather than implement individual systems for each of these.

**Comment by colons** [comment]
we talked about this a bit already, but: this issue is about automatically-derived aliases for searching, #285 is about information that could be surfaced on song pages for everyone and would require sensible validation, #225 is about a boolean that would only be of interest to staff, and #215 is about a public boolean. i don't understand how these are particularly related or how combining them in the UI would be helpful. any public surfacing of this kind of information should be more considered than would be possible if these were generic tags

certainly, if there's track-specific information that we want elfs to be able to edit, that should all be presented on one form, but i don't understand why we'd want it to be part of something it makes sense to call a 'tagging system'

**Comment by colons** [comment]
https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting this is making me think this might not work for our purposes. we could fetch them gradually, perhaps as people visit anime pages, but that won't help with searches for stuff that nobody remembers the name of

i'll maybe have a dig to see if anyone's got a bulk export of this kind of data we could use instead
